### PR TITLE
Remove elm production warning

### PR DESCRIPTION
**Pull request by jouderianjr**
Hello @dillonkearns, I'm not very proud of this fix but it is a quick workaround in order to remove the annoying warning message :)

### CODE REVIEW

**Comment by dillonkearns** [comment]
If we wanted to, we could preserve the original `console.warn` function and then restore it after running the Elm part of the process like I do here:

https://github.com/dillonkearns/elm-pages/blob/master/generator/src/compile-elm.js#L12-L29

But that might be unnecessary. How about we add a simple comment there that points to this issue and the relevant context in case our future selves get confused?

**Comment by dillonkearns** [comment]
Thanks for opening the PR! 😄

**Comment by jouderianjr** [comment]
> If we wanted to, we could preserve the original `console.warn` function and then restore it after running the Elm part of the process like I do here:
> 
> https://github.com/dillonkearns/elm-pages/blob/master/generator/src/compile-elm.js#L12-L29
> 
> But that might be unnecessary. How about we add a simple comment there that points to this issue and the relevant context in case our future selves get confused?

yeah, even if it is not exactly necessary, restore the `console.warn` will avoid unexpected behavior.

I also added a comment, let me know about the text, I can change as you prefer 💃

**Comment by dillonkearns** [comment]
👍 Thanks for making a PR for this @jouderianjr!

**Pull request merged**
