### PR TITLE
Switch discardParsedErrorData from returning a () to an unconstrained a

### PR DESCRIPTION
**Pull request by Jayshua**
As discussed in #224

### CODE REVIEW

**Comment by Jayshua** [comment]
Turned out it didn't even need the `never` call at all. 🤷‍♂

**Comment by dillonkearns** [comment]
Wow, that's nice and simple then. Thanks for this nice refinement 👍

I don't have access to a computer for a couple of weeks. I just gave you push access, though, so you can merge it and do an Elm package release (since Elm let's you publish if you can create a git tag). If you do a release, would you mind updating the Elm package release notes markdown file, too?

**Comment by Jayshua** [comment]
I'm happy to try stumbling through it :) Never published an Elm package before, so I'll have to look up how its done. Shall report back when I get a chance to work through it.

**Comment by dillonkearns** [comment]
I published this in the latest release! https://github.com/dillonkearns/elm-graphql/blob/master/CHANGELOG-ELM-PACKAGE.md#500---2019-12-16

Thanks again!

**Pull request merged**
