### PR TITLE
Add support for specifying an operation name

### LINKED ISSUE #123: Add support for operation name
We use the `OperationName` for "tagging" queries so we can separate them in our APM. 
Example: 

Screen Shot 2019-04-29 at 10 18 51 AM

This helps us diagnose performance issues in particular query-groups. Since we can't do that in elm, they all get lumped into our "web requests" as a catch-all, so there's no way to distinguish real queries versus types that wrap APIs, for example. 

Would it be possible for elm-graphql to do this? 

Thanks for all your work on this library!

### PR DESCRIPTION
**Pull request by asterite**
Fixes #123

## What is this?

This adds Graphql.Http.withOperationName so you can write something like:

```elm
makeRequest : Cmd Msg
makeRequest =
    query
        |> Graphql.Http.queryRequest "https://elm-graphql.herokuapp.com"
        |> Graphql.Http.withOperationName "SayHello"
        |> Graphql.Http.send (RemoteData.fromResult >> GotResponse)
```

The operation name is specified in the GrpahQL docs:
https://graphql.org/learn/queries/#operation-name

The operation name is a meaningful and explicit name for your operation. It is only required in multi-operation documents, but its use is encouraged because it is very helpful for debugging and server-side logging.

## Implementation details

There were two ways to implement this:
- Modify the functions in `Grapqhl.Document` like `serializeQuery` to take an extra `Maybe String` operation name. Because `Grapqhl.Document` is public API this would be a breaking change.
- Add new functions to `Grpahql.Document` like `serializeQueryWithOperationName`. This is probably uglier but it's backwards compatible, so users upgrading to this newer version won't have to change anything if they don't want to (though it's unlikely that they use `Graphql.Document`, which sees like a very low level API... any reason to expose this to users?)

I chose the second option because it's the safer one, but let me know if you'd prefer the first one.

Also let me know if this is okay or you need me to do some changes, I'm happy to work on this!

## Note

I added some tests and I think this should work but I couldn't try it out on a local project because elm doesn't support pointing to local packages. I tried using [this method](https://stackoverflow.com/a/44469731/4990850) but it doesn't work for me because `elm-graphql` also provides a binary and my build fails if the binary is not there.

### CODE REVIEW

**Comment by asterite** [comment]
CI failed but I don't understand why. It seems it's running `bin/approve` and that's failing because of generate code/docs, but running `bin/approve` locally gives me an error:

```
up to date in 0.025s

> @dillonkearns/elm-graphql@3.6.2 build /Users/asterite/Projects/elm-graphql
> parcel build generator/src/elm-graphql.ts --out-file bundle.js --target node --bundle-node-modules --no-source-maps

sh: parcel: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! @dillonkearns/elm-graphql@3.6.2 build: `parcel build generator/src/elm-graphql.ts --out-file bundle.js --target node --bundle-node-modules --no-source-maps`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the @dillonkearns/elm-graphql@3.6.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/asterite/.npm/_logs/2019-08-21T13_24_10_810Z-debug.log
```

**Comment by asterite** [comment]
Oops, sorry, it seems I needed to install `parcel`. Once I did that `bin/approve` works correctly and without errors... 🤔

**Comment by pellebirkstrom** [comment]
Can this be merged? Would be very useful for our setup!

**Comment by dillonkearns** [comment]
Thank you so much @asterite! I just pushed a new release https://github.com/dillonkearns/elm-graphql/blob/master/CHANGELOG-ELM-PACKAGE.md#440---2019-10-14

I totally agree with your assessment of the different tradeoffs in the design 👍Might be something the revisit the next time there's a breaking change elsewhere in the package.

**Pull request merged**
