### PR TITLE
Integrate Murmur3 module

### PR DESCRIPTION
**Pull request by neslinesli93**
Hi, there is a problem with a compilation of this library due to a missing dependency, as stated in [the Murmur3 repo](https://github.com/robinheghan/murmur3/issues/5).

Since we don't know if the repo is actively maintained, copying the Murmur3 module inside `elm-graphql` seems a good compromise. I would also evaluate alternatives like hashing libraries with smaller footprint

### CODE REVIEW

**Comment by wilkoetsier** [comment]
@neslinesli93 perhaps you can request a review from @dillonkearns

**Comment by neslinesli93** [comment]
> @neslinesli93 perhaps you can request a review from @dillonkearns

I can't seem to be able to do it from the UI, maybe the reviews/assignee are disabled for this repo

**Comment by dillonkearns** [comment]
Thank you for finding this issue and getting a fix for it @neslinesli93! I'll get this released so people don't have any issues installing `elm-graphql`.

> I would also evaluate alternatives like hashing libraries with smaller footprint

If we want to explore this further, maybe we can open a new issue to discuss. But I'm curious what you mean by libraries with a smaller footprint. What about this library's footprint is large? The module itself is small. Have you noticed some sort of performance bottleneck from this dependency? Or something else?

**Comment by dillonkearns** [comment]
The release is live now 👍 

https://package.elm-lang.org/packages/dillonkearns/elm-graphql/latest/about

https://github.com/dillonkearns/elm-graphql/blob/master/CHANGELOG-ELM-PACKAGE.md#502---2020-09-17

**Comment by neslinesli93** [comment]
> Thank you for finding this issue and getting a fix for it @neslinesli93! I'll get this released so people don't have any issues installing `elm-graphql`.
> 
> > I would also evaluate alternatives like hashing libraries with smaller footprint
> 
> If we want to explore this further, maybe we can open a new issue to discuss. But I'm curious what you mean by libraries with a smaller footprint. What about this library's footprint is large? The module itself is small. Have you noticed some sort of performance bottleneck from this dependency? Or something else?

Thanks for the quick response :)

When I first opened the issue I didn't know exactly what was the need for an hashing function inside this library... I was just wondering if there was some kind of hashing function in the standard library, or roll our own. But after seeing that there are many JS dependency related to the murmur algorithm, maybe we can just keep it this way

**Comment by dillonkearns** [comment]
Got it, thanks for clarifying.

I go into the reason for the hashing in this post: https://medium.com/@dillonkearns/how-elm-guides-towards-simplicity-3d34685dc33c. In a nutshell, that's how `elm-graphql` is able to avoid defining field aliases in your Elm code. That would introduce another point of failure, and `elm-graphql` can guarantee that you will never have any colliding fields in your queries. The post gives more details.

I haven't seen any issues with using this specific library for that, so unless we have some specific issues with it I think it's okay the way it is 👍

**Comment by oleks** [comment]
That's a fun fix, but remember to make due reference to the original author. (And to mention the copyright holder.)

**Comment by opsb** [comment]
Many thanks for the quick turnaround this @neslinesli93 @dillonkearns!

**Comment by sporto** [comment]
What is the proper way to remove the mumur dependecy?

I update elm-graph in `elm-json`
Remove `mumur` in `indirect`
Delete ~./elm

Run elm make and get

```
-- ERROR IN DEPENDENCIES ---------------------------------------------- elm.json

It looks like the dependencies elm.json in were edited by hand (or by a 3rd
party tool) leaving them in an invalid state.
```

**Comment by sporto** [comment]
Got it now, I had another dep using mumur too `elm-css`. I just had to update both at the same time.

**Pull request merged**
